# Generated by Django 4.2.6 on 2023-10-21 14:01

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_uploadedtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedtext",
            name="date",
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
