# Generated by Django 4.2.6 on 2023-10-21 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_uploadedtext_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daydata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
