# Generated by Django 4.2.6 on 2023-10-21 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
