# Generated by Django 4.2.6 on 2023-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_uploadedfile_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="daydata",
            name="practice_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
