# Generated by Django 4.2.6 on 2023-10-22 15:20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0007_daydata_practice_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daydata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="daydata", unique_together={("user", "date")},
        ),
    ]
