# Generated by Django 4.2.6 on 2023-10-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("educator", "0010_studygroup_practice_goal"),
        ("student", "0008_alter_daydata_date_alter_daydata_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="daydata", unique_together=set(),),
        migrations.AddField(
            model_name="daydata",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="educator.studygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="educator.studygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedtext",
            name="group",
            field=models.ForeignKey(
                default="000000",
                on_delete=django.db.models.deletion.CASCADE,
                to="educator.studygroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="daydata", unique_together={("user", "date", "group")},
        ),
    ]
