# Generated by Django 4.2.6 on 2023-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_joingroup_join_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joingroup",
            name="join_code",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
