# Generated by Django 4.2.6 on 2023-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0018_alter_userprofile_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
