# Generated by Django 4.2.6 on 2023-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="join_code",
            field=models.CharField(default="W6OT1S", max_length=6, unique=True),
        ),
    ]
