# Generated by Django 4.2.6 on 2023-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educator", "0007_alter_studygroup_join_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="join_code",
            field=models.CharField(max_length=6),
        ),
    ]
