# Generated by Django 4.2.6 on 2023-10-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("educator", "0008_alter_studygroup_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="educator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educator_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
